### ISSUE TITLE
manifest.webmanifest warning

### ISSUE THREAD

**Issue by Brouilles** [JohnPremKumar/vite-plugin-favicons-inject#12]
```
manifest.webmanifest:1 
        
       Manifest: property 'name' ignored, type string expected.
manifest.webmanifest:1 
        
       Manifest: property 'short_name' ignored, type string expected.
manifest.webmanifest:1 
        
       Manifest: property 'description' ignored, type string expected.
``` 

All values are `null`.
How to set them? The same configuration than https://github.com/josh-hemphill/vite-plugin-favicon#advanced-usage doesn't work.

**Comment by oliverseddon** [comment]
Not sure if you found the solution or not, I think the docs could do with being updated to show an example of how to add the additional config.

vitePluginFaviconsInject(
  '/src/assets/favicon.svg',
  {
    appName: 'My Great App',
    appDescription:  'This is the best app, and also a great description',
  }
)
