### ISSUE TITLE
Plugin teies to create pwa manifest and not working

### ISSUE THREAD

**Issue by inu255** [JohnPremKumar/vite-plugin-favicons-inject#18]
Hi everyone!

I'm trying set favicon. Here is my vite config file:

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
import checker from "vite-plugin-checker";
import vitePluginFaviconsInject from "vite-plugin-favicons-inject";

export default defineConfig({
  build: {
    outDir: "./public",
  },
  server: { port: 8082 },
  plugins: [
    react(),
    tsconfigPaths(),
    checker({ typescript: true, stylelint: false }),
    vitePluginFaviconsInject("./src/favicon.svg"),
  ],
  css: {
    preprocessorOptions: {
      less: {
        ...
      },
    },
  },
});

```

Result:
![image](https://user-images.githubusercontent.com/47324967/234194856-fa8a72ba-8a7a-4a53-aa2a-1370d4fa11a9.png)
And of course there is no favicon appears in the browser tab.

Looks like the plugin tries to create pwa manifest, but it's quite an overkill for my app. I need to set plain svg or ico favicon. Can anyone help me?

**Comment by JohnPremKumar** [comment]
As mentioned here(https://github.com/JohnPremKumar/vite-plugin-favicons-inject#development-mode). The files will be generated only during production build. Refer the link for more information

**Comment by inu255** [comment]
> As mentioned here(https://github.com/JohnPremKumar/vite-plugin-favicons-inject#development-mode). The files will be generated only during production build. Refer the link for more information

It works! Thank you very much!
