### ISSUE TITLE
path.join flips // to \ in windows

### ISSUE THREAD

**Issue by bradder555** [JohnPremKumar/vite-plugin-favicons-inject#6]
In windows, path.join("before","./","./","after") has the behavior of returning "before\after":
![image](https://user-images.githubusercontent.com/17851543/200153677-558fb02b-390d-477a-8d84-d3e42433afa1.png)

Obviously creates issues when used for a URL on this line:
https://github.com/JohnPremKumar/vite-plugin-favicons-inject/blob/18608ca22363a55de512f3fb847b4d8c311a6f30/src/index.js#L41

perhaps use new URL instead?
``` js
const fullUrl = new URL(path.join(path1, path2), baseUrl).toString();
```
https://javascript.plainenglish.io/how-to-safely-concatenate-url-with-node-js-f6527b623d5

I have a short-term workaround, in my vite.config.js file:
``` js
import { defineConfig } from 'vite'
import vitePluginFaviconsInject from 'vite-plugin-favicons-inject';

export default defineConfig({
  plugins: [
    vitePluginFaviconsInject(
      './src/assets/favicon.svg'
      )
  ],
  build: {
    sourcemap: true,
    outDir: "./dist",
    assetsDir: "assets"   
  },
  root: "./",
  base: "./"
});
```

**Comment by JohnPremKumar** [comment]
Thank you for the information. 

Will look into it!

**Comment by perwramdemark** [comment]
> 

Thanks this helped me! Had the same issue

**Comment by Brouilles** [comment]
I have the same issue.

**Comment by Brouilles** [comment]
Any news @JohnPremKumar ?
Because the workaround proposed before is not possible for me.

**Comment by JohnPremKumar** [comment]
Will check and update the package soon.

**Comment by Brouilles** [comment]
`config.path = opPath.replace('\\', '');` also work if you search a very quick fix.
